import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import React from 'react'
import useSWR from 'swr';
import { Anime } from '../../interface';


const fetcher = (url:string) => fetch(url).then(res=>res.json());
const AnimeDetails = () => {
    const router = useRouter();
    const { animeId } = router.query;
    const { data,error } = useSWR(`https://api.jikan.moe/v4/anime/${animeId}`,fetcher);
    const { data:anime } = data || {};
    if(error) return <h1>{error}</h1>

  return (
    <main className='max-w-8xl mx-auto'>
        <Head>
            <title>{anime?.title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
      </Head>
        {anime ? (
            <div className='relative'>
                <Image alt={anime.title} src={anime.images.webp.large_image_url} width="100%" height={25} layout="responsive" objectFit='cover'  />
                <div className='absolute -bottom-40 left-6'>
                  
                        <Image alt={anime.title} src={anime.images.webp.large_image_url}  width={220} height={300} className="rounded-lg" objectFit='cover' />

                </div>
            </div>
        ):(
            <p>loading...</p>
        )}
    </main>
  )
}

export default AnimeDetails