import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import HomeFeed from '../components/HomeFeed'
import Sidebar from '../components/Sidebar'
import { Anime } from '../interface'
import styles from '../styles/Home.module.css'
import { getAnimeByFilter, getSeasonNowAnime, getSeasonYearAnime } from './api/anime'

interface IProps {
  seasonsNow:Anime[];
  seasonYear:Anime[];
  topAiring:Anime[];
  topUpcoming:Anime[];
}

const Home = ({ seasonsNow,seasonYear,topAiring,topUpcoming }:IProps) => {
  const homeFeed = {
    seasonsNow,
    seasonYear,

  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeFeed {...homeFeed} />

      {/* <div className=''>
        {seasonsNow?.map((anime:any)=>(
          <div key={anime.mal_id}>
               <h1 key={anime.mal_id}>{anime.title}</h1>
              <p>{anime.season}</p>
          </div>
     
        ))}
      </div> */}

    </div>
  )
}

export const getStaticProps = async() => {
  const [seasonsNow,seasonYear] = ([await getSeasonNowAnime(),await getSeasonYearAnime(2022,'spring')]);

  return {
    props:{
      seasonsNow,
      seasonYear,
      
    },
    
  }

}

export default Home
